spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: hyejin
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      use-new-id-generator-mappings: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp